### ISSUE TITLE
Mixed Template (RectangleLabels and TextArea) causes error, when i editing input with TextArea

### ISSUE THREAD

**Issue by motionrus** [heartexlabs/label-studio-frontend#1033]
Template with RectangleLabels and TextArea causes error when editing input with TextArea, when I test individually, editing the TextArea Works
```
Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_reactName%2C%20_targetInst%2C%20type%2C%20nativeEvent%2C%20target%2C%20currentTarget%2C%20eventPhase%2C%20bubbles%2C%20cancelable%2C%20timeStamp%2C%20defaultPrevented%2C%20isTrusted%2C%20isDefaultPrevented%2C%20isPropagationStopped%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Si (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Fa (react-dom.production.min.js:176:186)
    at $s (react-dom.production.min.js:271:134)
    at Nl (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)
    at Rl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
    at Xo (react-dom.production.min.js:123:61)
    at Yo (react-dom.production.min.js:122:428)
    at react-dom.production.min.js:244:114
    at De (react-dom.production.min.js:292:136)
    at ze (react-dom.production.min.js:49:410)
    at react-dom.production.min.js:50:81
    at Dr (react-dom.production.min.js:105:469)
    at Zt (react-dom.production.min.js:75:265)
    at Jt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
    at je (react-dom.production.min.js:292:48)
    at Xt (react-dom.production.min.js:73:352)
    at HTMLDivElement.r (helpers.js:72:23)

Uncaught Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_reactName%2C%20_targetInst%2C%20type%2C%20nativeEvent%2C%20target%2C%20currentTarget%2C%20eventPhase%2C%20bubbles%2C%20cancelable%2C%20timeStamp%2C%20defaultPrevented%2C%20isTrusted%2C%20isDefaultPrevented%2C%20isPropagationStopped%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Si (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Fa (react-dom.production.min.js:176:186)
    at $s (react-dom.production.min.js:271:134)
    at Nl (react-dom.production.min.js:250:347)
    at Pl (react-dom.production.min.js:250:278)
    at Rl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
    at Xo (react-dom.production.min.js:123:61)
    at Yo (react-dom.production.min.js:122:428)
    at react-dom.production.min.js:244:114
    at De (react-dom.production.min.js:292:136)
    at ze (react-dom.production.min.js:49:410)
    at react-dom.production.min.js:50:81
    at Dr (react-dom.production.min.js:105:469)
    at Zt (react-dom.production.min.js:75:265)
    at Jt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Go (react-dom.production.min.js:122:325)
    at je (react-dom.production.min.js:292:48)
    at Xt (react-dom.production.min.js:73:352)
    at HTMLDivElement.r (helpers.js:72:23)
```

Template for example
```
  <View>
    <Image name="image" value="$image"/>
    <Header value="Выделите ответы на вопросы:"/>
    <RectangleLabels name="label" toName="image">
      <Label value="Q1" background="#E6194B"/>
    </RectangleLabels>
    <Header value="Введите вопросы:"/>
    <View style="display: flex; height: 40px;">
      <View style="flex: 10%; background-color: #E6194B">
        <Header value="Q1:" style="text-align: right;"/>
      </View>
      <View style="flex: 90%">
        <TextArea name="Q1" editable="true" toName="image" placeholder="Введите вопрос..." maxSubmissions="1"/>
      </View>
    </View>
  </View>

```

**Comment by makseq** [comment]
Just checked it with the latest LS version from the develop branch (1.6) and it works fine. 

https://user-images.githubusercontent.com/501780/204424508-f3e18eab-1a23-4abf-a684-34e0488c5897.mp4

**Comment by motionrus** [comment]
creating and deleting TextArea works well, but editing does not work

> Just checked it with the latest LS version from the develop branch (1.6) and it works fine.
> 
>  some.mp4
